version: '3.9'

networks:
  default:
    name: 'merus-power-demo-network'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "y"
      MSSQL_SA_PASSWORD: "comPL3x-p4SSw0rd" 
    