version: '3.9'

networks:
  default:
    name: 'azure-functions-demo-network'

services:
  productcatalog.api:
    image: ${DOCKER_REGISTRY-}product-catalog.api
    container_name: product-catalog.api
    ports:
      - 32741:80
    depends_on:
      - sqlserver
    build:
      context: .
      dockerfile: Products.API/Dockerfile
    environment:
      AzureWebJobsSecretStorageType: "files"
      FUNCTIONS_WORKER_RUNTIME: "dotnet-isolated"
      SQL_CONNECTION_STRING: "Server=sqlserver; Database=ProductCatalog; Encrypt=True; TrustServerCertificate=True; User ID=sa; Password=comPL3x-p4SSw0rd"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    restart: always
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "y"
      MSSQL_SA_PASSWORD: "comPL3x-p4SSw0rd"
